title:            Shixing Wang
tagline:          "Shixing Wang's Personal Website"
description:      Shixing Wang works as a postdoc at the physics department of Washington University in St. Louis. He studies organelle biogenesis as the main job, while having several side projects and even more hobbies.
url:              https://shixingwang.github.io
baseurl_root:     ""
baseurl:          ""
permalink:        /:categories/:title
author:
  name:           'Shixing Wang'
  url:            https://twitter.com/wang_shixing
github:
  repo:           https://github.com/ShixingWang/shixingwang.github.io
languages:                  ["en", "zh-CN"]
exclude_from_localizations: ["public"]
lang_name:
  en:    En
  zh-CN: 汉